package lib

//oa_status oa_request
var OA_ENTRIED int64 = 258
var CS_APPROVED int64 = 259
var KYC_APPROVED int64 = 260
var CUSTOMER_BUILD int64 = 261
var SINVEST_DONE int64 = 262
var DRAFT int64 = 444

var USER_CAT_BRANCH int64 = 3

//ROLE GROUP
var ROLE_INSTITUTION_MAKER = "17"
var ROLE_INSTITUTION_CHECKER = "18"
var ROLE_INSTITUTION_RELEASER = "19"

//OA_REQ_TYPE
var OA_REQ_TYPE_NEW = "127"
var OA_REQ_TYPE_PENGKINIAN_DATA = "296"
var OA_REQ_TYPE_PENGKINIAN_RISIKO = "128"

//path
var INST_FILE_PATH = "/images/institution/files"

var MAX_FILE_SIZE = 2000000 //2MB
var MAX_FILE_SIZE_MB = "2"  //2MB

var PERSETUJUAN_TRANSAKSI = "PERSETUJUAN_TRANSAKSI"
var DALAM_PROSES = "DALAM_PROSES"
