package models

type OaRequestCsvFormat struct {
	Type                  string `json:"type"`
	SACode                string `json:"sa_code"`
	SID                   string `json:"sid"`
	FirstName             string `json:"first_name"`
	MiddleName            string `json:"middle_name"`
	LastName              string `json:"last_name"`
	CountryOfNationality  string `json:"country_of_nationality"`
	IDno                  string `json:"id_no"`
	IDExpirationDate      string `json:"id_expiration_date"`
	NpwpNo                string `json:"npwp_no"`
	NpwpRegistrationDate  string `json:"npwp_registration_date"`
	CountryOfBirth        string `json:"country_of_birthday"`
	PlaceOfBirth          string `json:"place_of_birth"`
	DateOfBirth           string `json:"date_of_birth"`
	Gender                string `json:"gender"`
	EducationalBackground string `json:"education_background"`
	MotherMaidenName      string `json:"mother_maiden_name"`
	Religion              string `json:"religion"`
	Occupation            string `json:"occupation"`
	IncomeLevel           string `json:"income_level"`
	MaritalStatus         string `json:"marital_status"`
	SpouseName            string `json:"spouse_name"`
	InvestorRiskProfile   string `json:"investor_risk_profile"`
	InvestmentObjective   string `json:"investment_objective"`
	SourceOfFund          string `json:"source_of_fund"`
	AssetOwner            string `json:"asset_owner"`
	KTPAddress            string `json:"ktp_address"`
	KTPCityCode           string `json:"ktp_city_code"`
	KTPPostalCode         string `json:"ktp_postal_code"`

	CorrespondenceAddress    string `json:"correspondence_address"`
	CorrespondenceCityCode   string `json:"correspondence_City_code"`
	CorrespondenceCityName   string `json:"correspondence_city_name"`
	CorrespondencePostalCode string `json:"correspondence_postal_code"`
	CountryOfCorrespondence  string `json:"country_of_correspondence"`

	DomicileAddress              string `json:"domicile_address"`
	DomicileCityCode             string `json:"domicile_city_code"`
	DomicileCityName             string `json:"domicile_city_name"`
	DomicilePostalCode           string `json:"domicile_postal_code"`
	CountryOfDomicile            string `json:"country_of_domicile"`
	HomePhone                    string `json:"home_phone"`
	MobilePhone                  string `json:"mobile_phone"`
	Facsimile                    string `json:"facsimile"`
	Email                        string `json:"email"`
	StatementType                string `json:"statement_type"`
	FATCA                        string `json:"fatca"`
	ForeignTIN                   string `json:"foreign_tin"`
	ForeignTINIssuanceCountry    string `json:"foreign_tin_issuance_country"`
	REDMPaymentBankBICCode1      string `json:"redm_payment_bank_bic_code1"`
	REDMPaymentBankBIMemberCode1 string `json:"redm_payment_bank_bi_member_code1"`
	REDMPaymentBankName1         string `json:"redm_payment_bank_name1"`
	REDMPaymentBankCountry1      string `json:"redm_payment_bank_country1"`
	REDMPaymentBankBranch1       string `json:"redm_payment_bank_branch1"`
	REDMPaymentACCcy1            string `json:"redm_payment_ac_ccy1"`
	REDMPaymentACNo1             string `json:"redm_payment_ac_no1"`
	REDMPaymentACName1           string `json:"redm_payment_ac_name1"`
	REDMPaymentBankBICCode2      string `json:"redm_payment_bank_bic_code2"`
	REDMPaymentBankBIMemberCode2 string `json:"redm_payment_bank_bi_member_code2"`
	REDMPaymentBankName2         string `json:"redm_payment_bank_name2"`
	REDMPaymentBankCountry2      string `json:"redm_payment_bank_country2"`
	REDMPaymentBankBranch2       string `json:"redm_payment_bank_branch2"`
	REDMPaymentACCcy2            string `json:"redm_payment_ac_ccy2"`
	REDMPaymentACNo2             string `json:"redm_payment_ac_no2"`
	REDMPaymentACName2           string `json:"redm_payment_ac_name2"`
	REDMPaymentBankBICCode3      string `json:"redm_payment_bank_bic_code3"`
	REDMPaymentBankBIMemberCode3 string `json:"redm_payment_bank_bi_member_code3"`
	REDMPaymentBankName3         string `json:"redm_payment_bank_name3"`
	REDMPaymentBankCountry3      string `json:"redm_payment_bank_country3"`
	REDMPaymentBankBranch3       string `json:"redm_payment_bank_branch3"`
	REDMPaymentACCcy3            string `json:"redm_payment_ac_ccy3"`
	REDMPaymentACNo3             string `json:"redm_payment_ac_no3"`
	REDMPaymentACName3           string `json:"redm_payment_ac_name3"`
	ClientCode                   string `json:"client_code"`
}

type OaRequestInstitutionCsvFormat struct {
	Type                                          string `json:"type"`
	SACode                                        string `json:"sa_code"`
	SID                                           string `json:"sid"`
	CompanyName                                   string `json:"company_name"`
	CountryOfDomicile                             string `json:"country_of_domicile"`
	SiupNo                                        string `json:"siup_no"`
	SiupExpirationDate                            string `json:"siup_expiration_date"`
	SkdNo                                         string `json:"skd_no"`
	SkdExpirationDate                             string `json:"skd_expiration_date"`
	NpwpNo                                        string `json:"npwp_no"`
	NpwpRegistrationDate                          string `json:"npwp_registration_date"`
	CountryOfEstablishment                        string `json:"country_of_establishment"`
	PlaceOfEstablishment                          string `json:"place_of_establishment"`
	DateOfEstablishment                           string `json:"date_of_establishment"`
	ArticlesOfAssociationNo                       string `json:"articles_of_association_no"`
	CompanyType                                   string `json:"company_type"`
	CompanyCharacteristic                         string `json:"company_characteristic"`
	IncomeLevelIDR                                string `json:"income_level_idr"`
	InvestorsRiskProfile                          string `json:"investors_risk_profile"`
	InvestmentObjective                           string `json:"investment_objective"`
	SourceOfFund                                  string `json:"source_of_fund"`
	AssetOwner                                    string `json:"asset_owner"`
	CompanyAddress                                string `json:"company_address"`
	CompanyCityCode                               string `json:"company_city_code"`
	CompanyCityName                               string `json:"company_city_name"`
	CompanyPostalCode                             string `json:"company_postal_code"`
	CountryOfCompany                              string `json:"country_of_company"`
	OfficePhone                                   string `json:"office_phone"`
	Facsimile                                     string `json:"facsimile"`
	Email                                         string `json:"email"`
	StatementType                                 string `json:"statement_type"`
	AuthorizedPerson1FirstName                    string `json:"authorized_person_1_first_name"`
	AuthorizedPerson1MiddleName                   string `json:"authorized_person_1_middle_name"`
	AuthorizedPerson1LastName                     string `json:"authorized_person_1_last_name"`
	AuthorizedPerson1Position                     string `json:"authorized_person_1_position"`
	AuthorizedPerson1MobilePhone                  string `json:"authorized_person_1_mobile_phone"`
	AuthorizedPerson1Email                        string `json:"authorized_person_1_email"`
	AuthorizedPerson1NpwpNo                       string `json:"authorized_person_1_npwp_no"`
	AuthorizedPerson1KTPNo                        string `json:"authorized_person_1_ktp_no"`
	AuthorizedPerson1KTPExpirationDate            string `json:"authorized_person_1_ktp_expiration_date"`
	AuthorizedPerson1PassportNo                   string `json:"authorized_person_1_passport_no"`
	AuthorizedPerson1PassportExpirationDate       string `json:"authorized_person_1_passport_expiration_date"`
	AuthorizedPerson2FirstName                    string `json:"authorized_person_2_first_name"`
	AuthorizedPerson2MiddleName                   string `json:"authorized_person_2_middle_name"`
	AuthorizedPerson2LastName                     string `json:"authorized_person_2_last_name"`
	AuthorizedPerson2Position                     string `json:"authorized_person_2_position"`
	AuthorizedPerson2MobilePhone                  string `json:"authorized_person_2_mobile_phone"`
	AuthorizedPerson2Email                        string `json:"authorized_person_2_email"`
	AuthorizedPerson2NpwpNo                       string `json:"authorized_person_2_npwp_no"`
	AuthorizedPerson2KTPNo                        string `json:"authorized_person_2_ktp_no"`
	AuthorizedPerson2KTPExpirationDate            string `json:"authorized_person_2_ktp_expiration_date"`
	AuthorizedPerson2PassportNo                   string `json:"authorized_person_2_passport_no"`
	AuthorizedPerson2PassportExpirationDate       string `json:"authorized_person_2_passport_expiration_date"`
	AssetInformationforThePast3YearsIDRLastYear   string `json:"asset_information_for_the_past_3_years_idr_last_year"`
	AssetInformationforThePast3YearsIDR2YearsAgo  string `json:"asset_information_for_the_past_3_years_idr_2_years_ago"`
	AssetInformationforThePast3YearsIDR3YearsAgo  string `json:"asset_information_for_the_past_3_years_idr_3_years_ago"`
	ProfitInformationforThePast3YearsIDRLastYear  string `json:"Profit_Information_for_the_Past_3_Years_idr_last_year"`
	ProfitInformationforThePast3YearsIDR2YearsAgo string `json:"Profit_Information_for_the_Past_3_Years_idr_2_years_ago"`
	ProfitInformationforThePast3YearsIDR3YearsAgo string `json:"Profit_Information_for_the_Past_3_Years_idr_3_years_ago"`
	FATCAStatus                                   string `json:"fatca_status"`
	TINForeignTIN                                 string `json:"tin_foreign_tin"`
	TINForeignTINIssuance_Country                 string `json:"tin_foreign_tin_issuance_country"`
	GIIN                                          string `json:"giin"`
	SubstantialUSOwnerName                        string `json:"substantial_us_owner_name"`
	SubstantialUSOwnerAddress                     string `json:"substantial_us_owner_address"`
	SubstantialUSOwnerTIN                         string `json:"substantial_us_owner_tin"`
	REDMPaymentBankBICCode1                       string `json:"redm_payment_bank_bic_code1"`
	REDMPaymentBankBIMemberCode1                  string `json:"redm_payment_bank_bi_member_code1"`
	REDMPaymentBankName1                          string `json:"redm_payment_bank_name1"`
	REDMPaymentBankCountry1                       string `json:"redm_payment_bank_country1"`
	REDMPaymentBankBranch1                        string `json:"redm_payment_bank_branch1"`
	REDMPaymentACCcy1                             string `json:"redm_payment_ac_ccy1"`
	REDMPaymentACNo1                              string `json:"redm_payment_ac_no1"`
	REDMPaymentACName1                            string `json:"redm_payment_ac_name1"`
	REDMPaymentBankBICCode2                       string `json:"redm_payment_bank_bic_code2"`
	REDMPaymentBankBIMemberCode2                  string `json:"redm_payment_bank_bi_member_code2"`
	REDMPaymentBankName2                          string `json:"redm_payment_bank_name2"`
	REDMPaymentBankCountry2                       string `json:"redm_payment_bank_country2"`
	REDMPaymentBankBranch2                        string `json:"redm_payment_bank_branch2"`
	REDMPaymentACCcy2                             string `json:"redm_payment_ac_ccy2"`
	REDMPaymentACNo2                              string `json:"redm_payment_ac_no2"`
	REDMPaymentACName2                            string `json:"redm_payment_ac_name2"`
	REDMPaymentBankBICCode3                       string `json:"redm_payment_bank_bic_code3"`
	REDMPaymentBankBIMemberCode3                  string `json:"redm_payment_bank_bi_member_code3"`
	REDMPaymentBankName3                          string `json:"redm_payment_bank_name3"`
	REDMPaymentBankCountry3                       string `json:"redm_payment_bank_country3"`
	REDMPaymentBankBranch3                        string `json:"redm_payment_bank_branch3"`
	REDMPaymentACCcy3                             string `json:"redm_payment_ac_ccy3"`
	REDMPaymentACNo3                              string `json:"redm_payment_ac_no3"`
	REDMPaymentACName3                            string `json:"redm_payment_ac_name3"`
	ClientCode                                    string `json:"client_code"`
}

type OaRequestCsvFormatFiksTxt struct {
	DataRow string `json:"data_row"`
}
